config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#splash'
  devise_for :users
  resources :users, only: [:index, :show, :new, :create]
  resources :categories, only: [:index, :show, :new, :create, :destroy] do
    resources :transactions, only: [:index, :show, :new, :create, :destroy]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :transactions, dependent: :destroy
  attribute :total_amount, :integer
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :category
  validates :description, presence: true
  validates :amount, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:splash] # Exempt 'splash' action from authentication

  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    categories_path
  end

  def after_sign_out_path_for(_resource)
    new_user_session_path
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all

    # Calculate total amount for each category
    @categories.each do |category|
      category.total_amount = category.transactions.sum(:amount)
    end
  end

  def show
    @category = Category.find(params[:id])
    @transactions = @category.transactions
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_path, notice: 'Category created successfully.'
    else
      render :new
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to categories_path, notice: 'Category was successfully destroyed.'
  end

  def transactions
    @category = Category.find(params[:category_id])
    @transactions = @category.transactions

    # Calculate total amount
    @total_amount = @transactions.sum(:amount)
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :splash
  def splash
    @user = User.new
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @category = Category.find(params[:category_id])
    @transactions = @category.transactions.order(created_at: :desc)
    @total_amount = @transactions.sum(:amount)
  end

  def show
    @transaction = Transaction.find(params[:id])
    @category = @transaction.category
  end

  def new
    @category = Category.find(params[:category_id])
    @transaction = @category.transactions.build
  end

  def create
    @category = Category.find(params[:category_id])
    @transaction = @category.transactions.build(transaction_params)

    if @transaction.save
      redirect_to category_transactions_path(@category), notice: 'Transaction created successfully.'
    else
      render :new
    end
  end

  def destroy
    @category = Category.find(params[:category_id])
    @transaction = @category.transactions.find(params[:id])
    @transaction.destroy
    redirect_to category_transactions_path(@category), notice: 'Transaction deleted successfully.'
  end

  private

  def transaction_params
    params.require(:transaction).permit(:description, :amount)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    if params[:id] == 'sign_out'
      sign_out(current_user)
      redirect_to new_user_session_path, notice: 'You have signed out.'
    else
      @user = current_user
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/index.html.erb
<%= stylesheet_link_tag 'category', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="navbar">
  <div class="nav-btn1">
    <%= link_to 'New category', new_category_path, class: 'btn btn-primary' %>
  </div>
  
  <div class="nav-btn1" style="float: right;">
    <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>
  </div>
</div>

<div class="row">
  <% @categories.each do |category| %>
    <div class="col-lg-4 col-md-6 col-sm-12 mb-4">
      <div class="card">
        <div class="total-transactions">
          <h2>Total Amount: $<%= category.total_amount %></h2>
        </div>
        <div class="card-header">
          <b><%= link_to category.name, category_transactions_path(category) %></b>
        </div>
        <div class="card-body">
          <% category.transactions.each do |transaction| %>
            <div class="transaction-details">
              <div class="card-details">
                <i class="icon <%= category.icon %>"></i>
              </div>
              <div class="details-right">
                <div class="card-details text-right">
                  <p class='text-muted'>Description: <b><%= transaction.description %></b></p>
                </div>
                <div class="card-details text-right">
                  <p> Amount: <b> $<%= transaction.amount %></b></p>
                </div>
                 <div class="button-link text-right">
                <%= link_to 'Delete Transaction', category_transaction_path(category, transaction), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-success' %>
              </div>
              </div>
              </div>
            </div>
          <% end %>
          <div class="button-links text-right">
          <%= link_to 'New transaction', new_category_transaction_path(category), class: 'btn btn-primary text-right' %>
          <%= link_to 'Delete Category', category_path(category), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-success' %>
        </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="nav-btn">
  <%= link_to 'Back', root_path, class: 'btn btn-secondary' %>
</div>

app/views/categories/new.html.erb
<%= form_for @category do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
 <div class="field">
  <%= f.label :icon %>
  <%= f.select :icon, options_for_select(['fas fa-home', 'fas fa-car', 'fas fa-coffee']), {}, { class: 'form-control' } %>
  <small class="text-muted">For icons, use Font Awesome classes.</small>
</div>
  <%= f.submit "Save" %>
<% end %>

app/views/categories/show.html.erb
<h1>Category Details</h1>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<!-- Add other category details if needed -->

<%= button_to 'Delete', category_path(@category), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" rel="stylesheet">
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-black">
   <div class="container-fluid text-white"> 
     <a class="navbar-brand"></a> 
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"> 
       <span class="navbar-toggler-icon"></span> 
     </button> 
    <div class="collapse navbar-collapse" id="navbarNav"> <!-- Fixed the id -->
       <ul class="navbar-nav ml-auto"> <!-- Added ml-auto to align items to the right -->
         <% if user_signed_in? %> 

          <li class="nav-item"> 
             <%= link_to "Home", root_path, class: "nav-link" %>
         </li>

         <li class="nav-item"> 
             <%= link_to "Nav one", '#' ,class: "nav-link" %>
           </li> 
  
           <li class="nav-item"> 
             <%= button_to "Sign Out", destroy_user_session_path, method: :delete, form_class: "nav-link" %> 
           </li> 
  
         <% else %> 
           
         <% end %> 
       </ul> 
     </div> 
 </nav>

app/views/static_pages/splash.html.erb
<%= stylesheet_link_tag "splash", media: "all", 'data-turbolinks-track': "reload" %>

<div style="text-align: center;  margin: 0 auto;">
  <h1 style="font-size: 2em; margin-bottom: 80px;">Welcome to my Budget App</h1>
  <p style="font-size: 1.2em; margin-bottom: 80px;">Please login or signup below</p>
  <div>
    <%= link_to "Sign Up", new_registration_path(@user), class: "btn btn-secondary btn-lg", style: "display: inline-block; width: 80%; font-size: 1.5em; padding: 10px 20px; text-align: center; text-decoration: none; color: #fff; background-color: #007bff; margin-bottom: 10px;" %>
    <%= link_to "Log In", new_session_path(@user), class: "btn btn-secondary btn-lg", style: "display: inline-block; width: 80%; font-size: 1.5em; padding: 10px 20px; text-align: center; text-decoration: none; color: #fff; background-color: #28a745; margin-bottom: 10px;" %>
  </div>
</div>

app/views/transactions/create.html.erb
<h1>Transactions#create</h1>
<p>Find me in app/views/transactions/create.html.erb</p>

app/views/transactions/index.html.erb
<%= stylesheet_link_tag 'transaction', media: 'all', 'data-turbolinks-track': 'reload' %>
<div class="card">
<div class="total-transactions">
  <h2>Total Amount: $<%= @total_amount %></h2>
</div>
  <div class="card-header">
    <h1 class="card-title">Transactions for <%= @category.name %></h1>
  </div>
  <div class="card-body">
  <div>
    <%= link_to 'Add a new transaction', new_category_transaction_path(@category), class: 'btn btn-primary btn-sm' %>
    </div>
    <% @category.transactions.each do |transaction| %>
      <div class="card  bg-white d-flex justify-content-between align-items-center">
        <div class="card-body">
          Description: <%= transaction.description %>
        </div>
        <div class="card-body">
        Amount: $<%= transaction.amount %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="card-footer">
    <%= link_to 'Back', categories_path, class: 'btn btn-secondary' %>
  </div>
</div>

app/views/transactions/new.html.erb
<%= form_with(model: @transaction, url: category_transactions_path(@category), local: true) do |f| %>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :amount %>
    <%= f.text_field :amount %>
  </div>

  <div class="field">
    <%= f.label :category_id %>
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </div>
  
  <%= f.submit 'Save' %>
<% end %>

app/views/transactions/show.html.erb
<p class="flex justify-between py-2">
  <span><strong>Name:</strong></span>
  <span><%= @transaction.description %></span>
</p>

<p class="border-y-4 py-2 flex justify-between">
  <span><strong>Amount:</strong></span>
  <span>$<%= @transaction.amount %></span>
</p>

<p class="border-b-4 py-2 flex justify-between">
  <span><strong>Category:</strong></span>
  <span><%= @transaction.category.name %></span>
</p>

<p class="py-2 flex justify-between">
  <span><strong>Created at:</strong></span>
  <span><%= @transaction.created_at %></span>
</p>

<div>
<%= button_to "Delete", category_transaction_path(@category, @transaction), method: :delete, class: "mt-5 ms-5 p-3 px-5 red-btn text-white rounded-md hover:bg-red-600 focus:outline-none focus:bg-red-600 drop-shadow-md" %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password_digest, style: "display: block" %>
    <%= form.text_field :password_digest %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h2>New user</h2>
<%= render "form", user: @user %>
<br>
<div>
  <%= link_to "Back to users", users_path %>
</div>
 

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>